- name: Wait for Kong Admin API to be ready
  ansible.builtin.uri:
    url: http://{{ ansible_host }}:8001/status
    method: GET
    status_code: 200
  register: kong_status
  retries: 30
  delay: 5
  until: kong_status.status == 200
  
  - name: Create Service
  ansible.builtin.uri:
    url: http://{{ ansible_host }}:8001/services
    method: POST
    body:
      name: "{{ kong_service_name }}"
      url: "{{ kong_upstream_url }}"
    body_format: json
    status_code: [201, 409]

- name: Create Route
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:8001/services/{{ kong_service_name }}/routes"
    method: POST
    body:
      paths:
        - "{{ kong_route_path }}"
    body_format: json
    status_code: [201, 409]

- name: Enable Key Auth
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:8001/services/{{ kong_service_name }}/plugins"
    method: POST
    body:
      name: key-auth
    body_format: json
    status_code: [201, 409]

- name: Enable Prometheus Plugin
  ansible.builtin.uri:
    url: http://{{ ansible_host }}:8001/plugins
    method: POST
    body:
      name: prometheus
    body_format: json
    status_code: [201, 409]
