kong_version: "3.9.0"
kong_download_path: "/tmp/kong.deb"

kong_service_name: my-service
kong_upstream_url: "https://httpbin.org"
kong_route_path: "/test"

pg_host: "127.0.0.1"
pg_port: 5432
pg_user: kong
pg_password: kong
pg_database: kong
